#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 72a23fac-47e9-499a-abdd-835a9d2859ce
# Source File: ..\Documents\SAPIEN\PowerShell Studio\Projects\Rename-Sledge\Rename-Sledge.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
UQIAAB+LCAAAAAAABACFUl1vgjAUfTfxP5A+LkEUNUqGfVgMiw/7iJi9LrW9SLfSklKc7tevUFg0
27KXe3vK4ZycA/EWqDqCPq+JIXg48Lz4Was3oMZLz5LmWkn+CWyFEiIqQO1lwoUBvUI3o7Ka3Daz
cIu5NTkVoj1k7azsdDc5iHJkTga1RtbqBXTFlcThaBwHPeieWRfYrPEiJOE0I9SfLSDyZ1FEfLJn
zF9O5yRi4XIeUYiDjty92iXYnUvAVvgS9uJKMGvnBZduVQc66N3VXNjkY4RTQ7SpyyaM8/qL6aU5
0U1dO13btraQgQZJIaklNTbcCm3kUb2Dfy/UnohXWxbC7lw1zf2j/otemqsP/4FwmShdWL0M4R41
X+BK0AEX87sWh540P3BJREN4JAXgLUi7/FQAO4BVKi07Dn7QhoM4uPqFvgCiY4WWUQIAAA==#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.144
     Generated on:       10/10/2017 10:34 AM
     Generated by:       twilson
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2017
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
2gMAAB+LCAAAAAAABAC9k0tLAzEQgO+C/yH0vGR33a5rIbsglV4EFVfUazadLcE8yiRpyb+3rVJF
QaGHMJd5MPMxL/YIwm4A4w33nOwUJ61pJxe0nHTnZ4Swe5QrabhaSAV3XEPXe44+rOnaOZb/ih5y
rp0DPSgJ7mB/eWKnnbCo5JCR50/WlBZ7ycg8KB8QWgPBI1cZeQi7GuIW4pN9A9MOTcNrUV+Ws2oK
xdWM5ceqPyl9dB50CgZ9kWZpt44uLGqXhLjfVBoQ8q00q1NYRTXWYzOW5bIueMX/Z71qlaSnuUVI
MzyJILzF2ANupICTbuPvMR7Nj0dj+fdf7t4BtbYVHtoDAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
gh4AAB+LCAAAAAAABADNWWtvoloX/m7ifyB+Oif1FPEy2qQ12SC29q2OF9S2mWSCuGUYEQxgkf76
d202yEVQe850zmkTda2913qeddkX8XaMFfMNW15HdmQGPtiaadyVqtdcqV0sMMztV0tTNUPWu5qO
B/IGt/uyZnRNa3O9tVe37NEwNVr8xIrDON4W35Umnu3gzfVcM5ama18TW/paZrKGyswsYFG/rpD/
MiPsdGdn4TsD7xxL1svMcLfQNeV/2JPMNTbuFs2m3FAaX7ibWh1XWjclxgAqd6UV+CN0S4zyQ9OX
FkwtCabhWKZu0/CA69Ayt9hyvMAG7Rxzosg67mgbbBAeMPVLmeFqt2w49Zxp31ziUrsLSGdtBF3D
hjPR3sGg0eAAp9U4a0QSXWqH0Z2dPnFkyxmatuZANKW2AIDYmigWxudtJbx3SCj6ElvMGINSM1Rm
ouOlipkHebPB1rEP8Q0gAgekpoJu2ngZMf4eKW9Zf3KW5ZMpx22ImJp9vs0Ifd7cf3qnOYCzMPcD
7Pq1OdFvGW1jKD9Mq9SWzG2ZecIrp8yMNfXHce8cmz6ZikyLytXKTKt6gQntnSTfC8xoh9br9TJT
rVwwX5IXPWOJ96X2JaRolwEbJug0wor5A++vGa5ZbQ7mXeYvBoZ1j5njpQ2zzCWUr2co1zAg6PgN
67KxLDPS4M/jdmRpn/xnu2YoOz/+pZbhjjebMy1DyH5qv1w0O74rEUa0V759s7EFZ9g3mE5qbH/j
mtvw459MluP4hgP16piukQj1e6BM7Twfbil+5zim8ekdtfBh/A3/0Vz8g6b6eDvVGw3op+qXixsq
yfXinmoCTPX4MD7VUtzFLeWfcJfsh1MbC+ZmC7EvdExswRKaEQ5HSKC1u9DFTLN3sj5xPB3zsrIW
TN0vQI59vFfh3qCs0zn87mtPtGpSuGAjhDuQ9fnbIEEB+pIFOcBWKesyIPnhpmZ+l1LhfjS+3kZW
8ZNmO58eo0aQdECiGwG/sz1kgJKuney7l89u4lhY3sRWLQ/XbctrIyQihDos+UMjFP71kQqv3aWE
nweV13llN6vqu9f7m5riNe4XtUdH8Vx1tpl5SlV/W/ysVJ5+ol2x0Bfq7pPAd5bzfWX5/KgP5w19
+Tz2Xuau3evy3Mtmv32pODqejd/k6mw3nPdqg6rIvbxPq31p/T64n7pfO+suYVIsIOH1BH7jcTHv
Gq/T/VapjaXlw6P+Mud0RSXxIHF83628jBTBjwOtO+CNxOn24ZWvCkS75qSxMeInoy5EK/ICycSr
yiN0/wL4vEjkMQJZYtFEhPefLJr2eGkkVosF3kX8QAVvE7UDiUII5D6kDY3ITFHlVZCHLcS6HRad
eQdu8GmnAj31gUXvU551+xxatXy5jwI9R/RfhVBvg34wAj0gsyQu0BMZqgAjasrTDEZUlI3Qy/GE
Wj2+WGDdwYxofI+gYfeQO/IeeAhnhvN82UfwZUji1wnRr1XCzZ9ZAw+Ug4+FUGDh5XmmUUeefXlE
akpn+h4o+0NU6XyhRuRJDeUYE/AW5/IOI9w0yYXI+xzuRE8R/GiLhXWYr1pOVO+h/nx+g7wdRqKM
Uk/qGQQa9Syq6WFkKCQ9jeL6Sk5+XYSiWgO3qNpuWG0/mvqBK+iHUSUiBDeNQPotxMis+sGTGtU0
F8Gv6WEk8jQ89sQd69cHBJoN0m8RhhiuJr8yo8xMxyowSec5qKnv+2aak59RPNO5eW7QdXoq0zej
HISYTD26dJ3WU/1EZC/RHeKllSDcjqOEbZLmox7lbR1xSebRi/qVrtN0FOlaxZFeQ6RGshJknywW
svJhh7VtJPMyiNe8OTpaQ0FNE6voqvKxNXGlhvpiYRZm/ijKiBOf2YepdZ2Xt3WcwzLj3FBT3bFO
1TSrYzOjFeNIj3HOCW4KjMxGxxzElEV8FaazQvfefo6FkjhP6eoicjd7PU8ot+wd8sY+t7ekKugm
95C8jh3knMjpk51ymwUjWaspLwv9DIRiIcTIqkD/xCrKQqD3kPM3mqgC/ROrLrZOa+7HztOMsy59
nqY8cTlnPPGU3hchhuA8zbpf5N0WTiAAt/S9I1pF6T5T47erdN4CbvE7UB6XC28P4ZmVeStQc87N
zLtouIekML+cyHxWVpoRd7oWzt192D3QpLf4K3KHH+bc4ck6FXkevgeo8N6FuzlbF2F6i2eRyKKV
yw9dKXh/aCGp1WHdhw6RkfsAHvsJGbyNQg1Uwh2ySOmT/BCZb5EoVySPDy6Rr0ZJOT1eLKQ1GR4M
iuAj8g33iUV2JLtEVhDhdgXcpsHIG8xEYsiaRVgRWBqdH3UUfZ1fRdFfoeeWGM6DmgYzXSQaBANm
GIj15Q5SemAJSCzJwgPJAs0KVniXIoIsDgnHjuv32wgw3ftVqKFyNOMyGexZwi3ABM2TH2227HOG
LugLh3yRqP18RTUHblIUN4lacO/ubtngi3X42OTcDyOWbNhb2cKGc3hsc9CkrJOPJZBt481C17Ad
ug40XntjK6ala4tf8ODhlj14TaPQRx2/A+OXP045j0h+x/w9QJbsaob6d7AqtVVj1Vxx3LJRkWvy
eaznjf5bYhJMC/96oINIW/6Wjf/m3P4/JuOBQIIeAAA=#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formMain = New-Object 'System.Windows.Forms.Form'
	$textboxNewName = New-Object 'System.Windows.Forms.TextBox'
	$textboxPath = New-Object 'System.Windows.Forms.TextBox'
	$buttonStartJob = New-Object 'System.Windows.Forms.Button'
	$timerJobTracker = New-Object 'System.Windows.Forms.Timer'
	$imagelistButtonBusyAnimation = New-Object 'System.Windows.Forms.ImageList'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formMain_Load = {
		#TODO: Initialize Form Controls here
		
	}
	
	$formMain_FormClosed = [System.Windows.Forms.FormClosedEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.FormClosedEventArgs]
		#Stop any pending jobs
		Stop-JobTracker
	}
	

	$buttonStartJob_Click = {
		#Create Variables
		$buttonStartJob.Enabled = $false
		$path = $textboxPath.Text
		$newname = $textboxNewName.Text
		$ACLStorageArray = @{ }
		$servername = "server"
		$driveletter = 'E'
		
		#Functions
		function TakethAway ($x)
		{
			$ACEStorageArray = @()
			
			#Get ACL
			$acls = get-acl -path $x.FullName
			
			#Backup ACEs & Inheritance For Object
			$acls.Access | %{ $ACEStorageArray += $_ }
			$protected = $acls.AreAccessRulesProtected
			
			#Disable Inheritance
			$acls.SetAccessRuleProtection($true, $false)
			#Strip All Permissions
			$acls.Access | %{ $acls.RemoveAccessRule($_) }
			
			#Add User Permissions to allow us to manipulate the folder after "SET-ACL"
			$NewRule = New-Object System.Security.AccessControl.FileSystemAccessRule("MIS\$env:UserName", "FullControl", "ContainerInherit, ObjectInherit", "None", "Allow")
			$NewRule2 = New-Object System.Security.AccessControl.FileSystemAccessRule("MIS\$env:UserName", "FullControl", "Allow")
			
			
			Write-Host -Message "Striping - " + $x
			
			#Add ACEs to ACL
			$acls.AddAccessRule($NewRule)
			$acls.AddAccessRule($NewRule2)
			
			#Set New Permissions
			$acls | Set-Acl -path $x.FullName
			
			#Package recorded intial permissions to passback
			$object = New-Object –TypeName PSObject
			$object | Add-Member –MemberType NoteProperty –Name inheritance –Value $protected
			$object | Add-Member –MemberType NoteProperty –Name acl –Value $ACEStorageArray
			
			#Pass recorded intial permissions back
			return $object
			
		}
		
		function Giveth ($x, $aceArray)
		{
			Write-Host -Message "Restoring permissions - " + $x
			$acls = get-acl -path $x.FullName
			$acls.Access | %{ $acls.RemoveAccessRule($_) }
			$aceArray.acl | %{ $acls.AddAccessRule($_); Write-Host -Message $_ }
			$acls.SetAccessRuleProtection($aceArray.inheritance,$false)
			Set-Acl $x.FullName $acls
		}
		
		
		Get-ChildItem -Path $path -Recurse | ForEach-Object { $ACLStorageArray[$_.Name] += (TakethAway($_)) }
		
		Write-Host "Closing Users conntection..."
		$strippedpath = $path -replace "\\\\" + $servername + "\\", ""
		$strippedpath = $strippedpath -replace "\\","\\\\"
		$pattern = '^.+ (?<FileId>\d+) (?<User>[^ ]+).+ (?<OpenFile>' + $driveletter + ':.+' + $strippedpath.ToUpper() +'\\.*)$'
		$openfiles = (openfiles /query /s $servername /v).ToUpper() | Select-String -Pattern $pattern | ForEach-Object { [void]($_.Line -match $pattern); $matches['OpenFile'] }
		Write-Host -Object $openfiles
		$openfiles | Sort-Object -Unique | ForEach-Object { openfiles /disconnect /s $servername /a * /op `"$_`" }
		
		
		Write-Host -Message "Renaming...."
		$p1 = (get-item $path).parent.FullName
		Rename-Item -Force $path $newname
		$p1 = $p1 + "\" + $newname
		Get-ChildItem -Path $p1 -Recurse | ForEach-Object {
			$acl = $ACLStorageArray[$_.Name];
			Giveth $_ $acl
			}
		
		
		$buttonStartJob.Enabled = $true
		
	}
	
	$textboxPath_KeyDown = [System.Windows.Forms.KeyEventHandler]{
		#Event Argument: $_ = [System.Windows.Forms.KeyEventArgs]
		if ($_.KeyCode -eq 'Enter' -and $buttonStartJob.Enabled)
		{
			$buttonStartJob_Click
			$_.SuppressKeyPress = $true
		}
	}
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formMain.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_textboxNewName = $textboxNewName.Text
		$script:MainForm_textboxPath = $textboxPath.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$textboxPath.remove_KeyDown($textboxPath_KeyDown)
			$buttonStartJob.remove_Click($buttonStartJob_Click)
			$formMain.remove_FormClosed($formMain_FormClosed)
			$formMain.remove_Load($formMain_Load)
			$timerJobTracker.remove_Tick($timerJobTracker_Tick)
			$formMain.remove_Load($Form_StateCorrection_Load)
			$formMain.remove_Closing($Form_StoreValues_Closing)
			$formMain.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formMain.SuspendLayout()
	#
	# formMain
	#
	$formMain.Controls.Add($textboxNewName)
	$formMain.Controls.Add($textboxPath)
	$formMain.Controls.Add($buttonStartJob)
	$formMain.AutoScaleDimensions = '6, 13'
	$formMain.AutoScaleMode = 'Font'
	$formMain.ClientSize = '551, 185'
	$formMain.Name = 'formMain'
	$formMain.StartPosition = 'CenterScreen'
	$formMain.Text = 'Folder Renaming Sledge Hammer'
	$formMain.add_FormClosed($formMain_FormClosed)
	$formMain.add_Load($formMain_Load)
	#
	# textboxNewName
	#
	$textboxNewName.Anchor = 'Top, Left, Right'
	$textboxNewName.Location = '13, 82'
	$textboxNewName.Name = 'textboxNewName'
	$textboxNewName.Size = '444, 20'
	$textboxNewName.TabIndex = 2
	$textboxNewName.Text = 'New Folder Name (ex. 1727NWF - Newly Weds Foods, Inc. - Cleveland, TN)'
	#
	# textboxPath
	#
	$textboxPath.Anchor = 'Top, Left, Right'
	$textboxPath.Location = '13, 15'
	$textboxPath.Name = 'textboxPath'
	$textboxPath.Size = '444, 20'
	$textboxPath.TabIndex = 0
	$textboxPath.Text = 'Folder Path (ex. \\server\Projects\17projects\) '
	$textboxPath.add_KeyDown($textboxPath_KeyDown)
	#
	# buttonStartJob
	#
	$buttonStartJob.Anchor = 'Top, Right'
	$buttonStartJob.Location = '455, 126'
	$buttonStartJob.Name = 'buttonStartJob'
	$buttonStartJob.Size = '75, 23'
	$buttonStartJob.TabIndex = 1
	$buttonStartJob.Text = 'Rename'
	$buttonStartJob.UseCompatibleTextRendering = $True
	$buttonStartJob.UseVisualStyleBackColor = $True
	$buttonStartJob.add_Click($buttonStartJob_Click)
	#
	# timerJobTracker
	#
	$timerJobTracker.add_Tick($timerJobTracker_Tick)
	#
	# imagelistButtonBusyAnimation
	#
	$Formatter_binaryFomatter = New-Object System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
	#region Binary Data
	$System_IO_MemoryStream = New-Object System.IO.MemoryStream (,[byte[]][System.Convert]::FromBase64String('
AAEAAAD/////AQAAAAAAAAAMAgAAAFdTeXN0ZW0uV2luZG93cy5Gb3JtcywgVmVyc2lvbj00LjAu
MC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWI3N2E1YzU2MTkzNGUwODkFAQAA
ACZTeXN0ZW0uV2luZG93cy5Gb3Jtcy5JbWFnZUxpc3RTdHJlYW1lcgEAAAAERGF0YQcCAgAAAAkD
AAAADwMAAAB2CgAAAk1TRnQBSQFMAgEBCAEAAZgBAAGYAQABEAEAARABAAT/ASEBAAj/AUIBTQE2
BwABNgMAASgDAAFAAwABMAMAAQEBAAEgBgABMP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/AP8A/wD/
AP8AugADwgH/AzUB/wM1Af8DwgH/MAADwgH/A1UB/wOCAf8DwgH/sAADNQH/AwAB/wMAAf8DNQH/
MAADggH/AzUB/wM1Af8DVQH/gAADwgH/AzUB/wM1Af8DwgH/IAADNQH/AwAB/wMAAf8DNQH/A8IB
/wNVAf8DggH/A8IB/xAAA8IB/wM1Af8DNQH/A8IB/wNVAf8DNQH/AzUB/wNVAf8EAAOSAf8DkgH/
A8IB/3AAAzUB/wMAAf8DAAH/AzUB/yAAA8IB/wM1Af8DNQH/A8IB/wOCAf8DNQH/AzUB/wOCAf8Q
AAM1Af8DAAH/AwAB/wM1Af8DwgH/A1UB/wOCAf8DwgH/A5IB/wOCAf8DggH/A5IB/3AAAzUB/wMA
Af8DAAH/AzUB/zAAA1UB/wM1Af8DNQH/A1UB/xAAAzUB/wMAAf8DAAH/AzUB/xAAA5IB/wOSAf8D
kgH/A8IB/3AAA8IB/wM1Af8DNQH/A8IB/zAAA8IB/wNVAf8DggH/A8IB/xAAA8IB/wM1Af8DNQH/
A8IB/xAAA8IB/wOSAf8DkgH/A8IB/zgAA8IB/wM1Af8DNQH/A8IB/zAAA8IB/wOCAf8DVQH/A8IB
/zAAA8IB/wPCAf8DkgH/A8IB/zQAA8IB/wPCAf80AAM1Af8DAAH/AwAB/wM1Af8wAANVAf8DNQH/
AzUB/wNVAf8wAAOSAf8DggH/A4IB/wOSAf8wAAPCAf8DwgH/A8IB/wPCAf8wAAM1Af8DAAH/AwAB
/wM1Af8wAAOCAf8DNQH/AzUB/wOCAf8wAAPCAf8DggH/A5IB/wOSAf8wAAPCAf8DwgH/A8IB/wPC
Af8wAAPCAf8DNQH/AzUB/wPCAf8wAAPCAf8DggH/A1UB/wPCAf8wAAPCAf8DkgH/A5IB/wPCAf80
AAPCAf8DwgH/EAADwgH/A8IB/xQAA8IB/wOCAf8DVQH/A8IB/zAAA8IB/wOSAf8DkgH/A8IB/zQA
A8IB/wPCAf9UAAPCAf8DwgH/A8IB/wPCAf8QAANVAf8DNQH/AzUB/wNVAf8wAAOSAf8DggH/A5IB
/wOSAf8wAAPCAf8DwgH/A8IB/wPCAf9QAAPCAf8DwgH/A8IB/wPCAf8DwgH/A8IB/wOSAf8DwgH/
A4IB/wM1Af8DNQH/A4IB/yQAA8IB/wPCAf8EAAPCAf8DggH/A5IB/wOSAf8wAAPCAf8DwgH/A8IB
/wPCAf9UAAPCAf8DwgH/BAADkgH/A4IB/wOCAf8DkgH/A8IB/wOCAf8DVQH/A8IB/yAAA8IB/wPC
Af8DwgH/A8IB/wPCAf8DkgH/A5IB/wPCAf80AAPCAf8DwgH/ZAADkgH/A5IB/wOSAf8DkgH/MAAD
wgH/A8IB/wPCAf8DwgH/sAADwgH/A5IB/wOSAf8DwgH/NAADwgH/A8IB/7QAA8IB/wPCAf8DkgH/
A8IB/zQAA8IB/wPCAf+0AAOSAf8DggH/A4IB/wOSAf8wAAPCAf8DwgH/A8IB/wPCAf+gAAPCAf8D
VQH/A4IB/wPCAf8DkgH/A5IB/wOSAf8DwgH/BAADwgH/A8IB/xQAA8IB/wPCAf8DkgH/A8IB/wPC
Af8DwgH/A8IB/wPCAf8kAAPCAf8DwgH/dAADggH/AzUB/wM1Af8DggH/A8IB/wOSAf8DkgH/A8IB
/wPCAf8DwgH/A8IB/wPCAf8QAAOSAf8DggH/A4IB/wOSAf8EAAPCAf8DwgH/JAADwgH/A8IB/wPC
Af8DwgH/cAADVQH/AzUB/wM1Af8DggH/EAADwgH/A8IB/wPCAf8DwgH/EAADkgH/A5IB/wOSAf8D
kgH/MAADwgH/A8IB/wPCAf8DwgH/cAADwgH/A1UB/wNVAf8DwgH/FAADwgH/A8IB/xQAA8IB/wOS
Af8DkgH/A8IB/zQAA8IB/wPCAf9sAAPCAf8DNQH/AzUB/wPCAf8wAAPCAf8DVQH/A4IB/wPCAf8w
AAPCAf8DwgH/A5IB/wPCAf80AAPCAf8DwgH/NAADNQH/AwAB/wMAAf8DNQH/MAADggH/AzUB/wM1
Af8DVQH/MAADkgH/A4IB/wOCAf8DkgH/MAADwgH/A8IB/wPCAf8DwgH/MAADNQH/AwAB/wMAAf8D
NQH/MAADVQH/AzUB/wM1Af8DggH/MAADkgH/A5IB/wOSAf8DkgH/MAADwgH/A8IB/wPCAf8DwgH/
MAADwgH/AzUB/wM1Af8DwgH/MAADwgH/A1UB/wNVAf8DwgH/MAADwgH/A5IB/wOSAf8DwgH/NAAD
wgH/A8IB/3wAA8IB/wM1Af8DNQH/A8IB/zAAA8IB/wNVAf8DggH/A8IB/zAAA8IB/wPCAf8DkgH/
A8IB/xAAA8IB/wM1Af8DNQH/A8IB/1AAAzUB/wMAAf8DAAH/AzUB/zAAA4IB/wM1Af8DNQH/A1UB
/zAAA5IB/wOCAf8DggH/A5IB/xAAAzUB/wMAAf8DAAH/AzUB/1AAAzUB/wMAAf8DAAH/AzUB/zAA
A1UB/wM1Af8DNQH/A4IB/wOSAf8DNQH/AzUB/wPCAf8gAAOSAf8DkgH/A5IB/wOSAf8DwgH/A1UB
/wOCAf8DwgH/AzUB/wMAAf8DAAH/AzUB/1AAA8IB/wM1Af8DNQH/A8IB/zAAA8IB/wOCAf8DVQH/
A8IB/wM1Af8DAAH/AwAB/wM1Af8gAAPCAf8DkgH/A5IB/wPCAf8DggH/AzUB/wM1Af8DVQH/A8IB
/wM1Af8DNQH/A8IB/6AAAzUB/wMAAf8DAAH/AzUB/zAAA1UB/wM1Af8DNQH/A4IB/7AAA8IB/wM1
Af8DNQH/A8IB/zAAA8IB/wOCAf8DVQH/A8IB/xgAAUIBTQE+BwABPgMAASgDAAFAAwABMAMAAQEB
AAEBBQABgAEBFgAD/4EABP8B/AE/AfwBPwT/AfwBPwH8AT8D/wHDAfwBAwHAASMD/wHDAfwBAwHA
AQMD/wHDAf8DwwP/AcMB/wPDAf8B8AH/AfAB/wHwAf8B+QH/AfAB/wHwAf8B8AH/AfAB/wHwAf8B
8AH/AfAB/wHwAf8B8AH/AfAB/wHwAf8B+QHnAcMB/wHDAf8B5wL/AsMB/wHDAf8BwwL/AcABAwH+
AUMB/wHDAv8B5AEDAfwBAwH/AecC/wH8AT8B/AE/BP8B/AE/Af4BfwT/AfwBPwH+AX8E/wH8AT8B
/AE/BP8BwAEnAcABPwHnA/8BwAEDAcIBfwHDA/8DwwH/AcMD/wHDAecBwwH/AecD/wEPAf8BDwH/
AQ8B/wGfAf8BDwH/AQ8B/wEPAf8BDwH/AQ8B/wEPAf8BDwH/AQ8B/wEPAf8BDwH/AQ8B/wGfA/8B
wwH/AcMB/wLDAv8BwwH/AcMB/wLDAv8BwwH/AcABPwHAAQMC/wHDAf8BwAE/AcABAwT/AfwBPwH8
AT8E/wH8AT8B/AE/Cw=='))
	#endregion
	$imagelistButtonBusyAnimation.ImageStream = $Formatter_binaryFomatter.Deserialize($System_IO_MemoryStream)
	$Formatter_binaryFomatter = $null
	$System_IO_MemoryStream = $null
	$imagelistButtonBusyAnimation.TransparentColor = 'Transparent'
	$formMain.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formMain.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formMain.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formMain.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formMain.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formMain.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
